apiVersion: v1
kind: ConfigMap
metadata:
  name: yatri-app-config-dev
  labels:
    app: yatri-backend
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  PORT: "5000"
  DEFAULT_CURRENCY: "INR"
  MAX_BOOKING_DAYS: "30"
